apiVersion: v1
kind: Pod
metadata:
  name: introspection-data-gather
  namespace: introspection-resources
  labels:
    app: introspection-data
spec:
  containers:
  - name: introspection-data-gather
    image: mfeinb02/introspection-data-gather:latest
  serviceAccountName: introspection-serviceaccount
  restartPolicy: Never
