docker:
	sudo docker build -f build/Dockerfile -t introspection-web-server .
	sudo docker tag introspection-web-server mfeinb02/introspection-web-server:latest
	sudo docker push mfeinb02/introspection-web-server:latest
