apiVersion: apps/v1
kind: Deployment
metadata:
  name: introspection-tool
  namespace: {{ .Release.Namespace }}
  labels:
    app: introspection-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: introspection-tool
  template:
    metadata:
      labels:
        app: introspection-tool
    spec:
      containers:
      - name: introspection-app-ctr
        image: mfeinb02/introspection-tool:latest
        env:
        - name: RATE
          value: "{{ .Values.rate }}"
        - name: WEB
          value: "{{ .Values.web }}"
        - name: FILEPATH
          value: "{{ .Values.path }}"
        ports:
        - containerPort: 443
      serviceAccountName: introspection-serviceaccount
---
apiVersion: v1
kind: Service
metadata:
  name: introspection-np
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 433
    nodePort: {{ .Values.nodePort }}
  selector:
    app: introspection-tool
