apiVersion: v1
entries:
  introspection-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-24T20:53:43.435948627Z"
    description: A Helm chart to deploy a Kubernetes cluster introspection tool
    digest: 7a1feb204331ab6f26abfeb90518f626fc39e58f3213dda1f15e77f773d0c8a2
    name: introspection-chart
    type: application
    urls:
    - https://MattFeinberg.github.io/K8s-Introspection-Tool/helm/introspection-chart-0.1.0.tgz
    version: 0.1.0
generated: "2022-08-24T20:53:43.435605021Z"
